/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/s63.glb --types -o src/components/Scene/Car/S63/Model.tsx -r public -k 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    DesireFXCOM_black_matt_06_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_36_black_matt_0: THREE.Mesh
    DesireFXCOM_tire_mat4_01_tire_mat4_0: THREE.Mesh
    DesireFXCOM_silver_19_silver_0: THREE.Mesh
    DesireFXCOM_chrome_24_chrome_0: THREE.Mesh
    DesireFXCOM_silver_20_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_37_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_29_black_shiny_0: THREE.Mesh
    DesireFXCOM_brakes2_02_brakes2_0: THREE.Mesh
    DesireFXCOM_black_shiny_28_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_47_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_d_03_silver_d_0: THREE.Mesh
    DesireFXCOM_black_matt_07_black_matt_0: THREE.Mesh
    DesireFXCOM_chrome_11_chrome_0: THREE.Mesh
    DesireFXCOM_silver_13_silver_0: THREE.Mesh
    DesireFXCOM_tire_mat4_03_tire_mat4_0: THREE.Mesh
    DesireFXCOM_black_matt_18_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_14_black_shiny_0: THREE.Mesh
    DesireFXCOM_brakes1_01_brakes1_0: THREE.Mesh
    DesireFXCOM_black_matt_19_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_16_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_32_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_d_01_silver_d_0: THREE.Mesh
    DesireFXCOM_black_matt_33_black_matt_0: THREE.Mesh
    DesireFXCOM_chrome_27_chrome_0: THREE.Mesh
    DesireFXCOM_silver_29_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_51_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_d_04_silver_d_0: THREE.Mesh
    DesireFXCOM_black_matt_48_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_50_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_26_black_matt_0: THREE.Mesh
    DesireFXCOM_tire_mat4_04_tire_mat4_0: THREE.Mesh
    DesireFXCOM_black_shiny_36_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_24_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_35_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_27_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_38_black_matt_0: THREE.Mesh
    DesireFXCOM_brakes2_01_brakes2_0: THREE.Mesh
    DesireFXCOM_black_shiny_33_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_shiny_21_black_shiny_0: THREE.Mesh
    DesireFXCOM_brakes1_02_brakes1_0: THREE.Mesh
    DesireFXCOM_black_matt_15_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_15_black_shiny_0: THREE.Mesh
    DesireFXCOM_tire_mat4_02_tire_mat4_0: THREE.Mesh
    DesireFXCOM_chrome_10_chrome_0: THREE.Mesh
    DesireFXCOM_silver_18_silver_0: THREE.Mesh
    DesireFXCOM_silver_d_02_silver_d_0: THREE.Mesh
    DesireFXCOM_black_matt_31_black_matt_0: THREE.Mesh
    DesireFXCOM_chrome_25_chrome_0: THREE.Mesh
    DesireFXCOM_body_02_body_0: THREE.Mesh
    DesireFXCOM_black_matt_28_black_matt_0: THREE.Mesh
    DesireFXCOM_glass_03_glass_0: THREE.Mesh
    DesireFXCOM_glass_bump_02_glass_bump_0: THREE.Mesh
    DesireFXCOM_chrome_12_chrome_0: THREE.Mesh
    DesireFXCOM_chrome_01_chrome_0: THREE.Mesh
    DesireFXCOM_black_10_black_0: THREE.Mesh
    DesireFXCOM_r_lights_02_r_lights_0: THREE.Mesh
    DesireFXCOM_r_glass_03_r_glass_0: THREE.Mesh
    DesireFXCOM_r_lights_01_r_lights_0: THREE.Mesh
    DesireFXCOM_chrome_22_chrome_0: THREE.Mesh
    DesireFXCOM_body_09_body_0: THREE.Mesh
    DesireFXCOM_r_glass_02_r_glass_0: THREE.Mesh
    DesireFXCOM_d_red_01_d_red_0: THREE.Mesh
    DesireFXCOM_red_02_red_0: THREE.Mesh
    DesireFXCOM_black_matt_16_black_matt_0: THREE.Mesh
    DesireFXCOM_r_glass_01_r_glass_0: THREE.Mesh
    DesireFXCOM_black_07_black_0: THREE.Mesh
    DesireFXCOM_body_10_body_0: THREE.Mesh
    DesireFXCOM_red_bump_01_red_bump_0: THREE.Mesh
    DesireFXCOM_black_matt_23_black_matt_0: THREE.Mesh
    DesireFXCOM_d_glass_02_d_glass_0: THREE.Mesh
    DesireFXCOM_black_09_black_0: THREE.Mesh
    DesireFXCOM_interior_09_interior_0: THREE.Mesh
    DesireFXCOM_red_01_red_0: THREE.Mesh
    DesireFXCOM_r_glass_04_r_glass_0: THREE.Mesh
    DesireFXCOM_silver_11_silver_0: THREE.Mesh
    DesireFXCOM_body_11_body_0: THREE.Mesh
    DesireFXCOM_black_04_black_0: THREE.Mesh
    DesireFXCOM_black_matt_13_black_matt_0: THREE.Mesh
    DesireFXCOM_interior_13_interior_0: THREE.Mesh
    DesireFXCOM_chrome_02_chrome_0: THREE.Mesh
    DesireFXCOM_body_15_body_0: THREE.Mesh
    DesireFXCOM_chrome_18_chrome_0: THREE.Mesh
    DesireFXCOM_chrome_19_chrome_0: THREE.Mesh
    DesireFXCOM_plate_01_plate_0: THREE.Mesh
    DesireFXCOM_r_glass_06_r_glass_0: THREE.Mesh
    DesireFXCOM_red_bump_02_red_bump_0: THREE.Mesh
    DesireFXCOM_body_04_body_0: THREE.Mesh
    DesireFXCOM_silver_30_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_11_black_matt_0: THREE.Mesh
    DesireFXCOM_chrome_16_chrome_0: THREE.Mesh
    DesireFXCOM_black_90_black_0: THREE.Mesh
    DesireFXCOM_interior_15_interior_0: THREE.Mesh
    DesireFXCOM_interior_03_interior_0: THREE.Mesh
    DesireFXCOM_vd_glass_90_vd_glass_0: THREE.Mesh
    DesireFXCOM_silver_05_silver_0: THREE.Mesh
    DesireFXCOM_interior_04_interior_0: THREE.Mesh
    DesireFXCOM_red_03_red_0: THREE.Mesh
    DesireFXCOM_black_matt_52_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_10_black_matt_0: THREE.Mesh
    DesireFXCOM_d_glass_01_d_glass_0: THREE.Mesh
    DesireFXCOM_black_shiny_11_black_shiny_0: THREE.Mesh
    DesireFXCOM_silver_07_silver_0: THREE.Mesh
    DesireFXCOM_silver_25_silver_0: THREE.Mesh
    DesireFXCOM_silver_28_silver_0: THREE.Mesh
    DesireFXCOM_black_shiny_18_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_40_black_matt_0: THREE.Mesh
    DesireFXCOM_black_15_black_0: THREE.Mesh
    DesireFXCOM_interior_02_interior_0: THREE.Mesh
    DesireFXCOM_black_03_black_0: THREE.Mesh
    DesireFXCOM_chrome_07_chrome_0: THREE.Mesh
    DesireFXCOM_chrome_15_chrome_0: THREE.Mesh
    DesireFXCOM_interior_b_01_interior_b_0: THREE.Mesh
    DesireFXCOM_silver_02_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_42_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_01_silver_0: THREE.Mesh
    DesireFXCOM_interior_10_interior_0: THREE.Mesh
    DesireFXCOM_black_shiny_19_black_shiny_0: THREE.Mesh
    DesireFXCOM_silver_06_silver_0: THREE.Mesh
    DesireFXCOM_black_05_black_0: THREE.Mesh
    DesireFXCOM_interior_01_interior_0: THREE.Mesh
    DesireFXCOM_interior_05_interior_0: THREE.Mesh
    DesireFXCOM_black_shiny_24_black_shiny_0: THREE.Mesh
    DesireFXCOM_tex_01_03_tex_01_0: THREE.Mesh
    DesireFXCOM_silver_16_silver_0: THREE.Mesh
    DesireFXCOM_silver_04_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_08_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_25_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_shiny_08_black_shiny_0: THREE.Mesh
    DesireFXCOM_silver_03_silver_0: THREE.Mesh
    DesireFXCOM_tex_01_01_tex_01_0: THREE.Mesh
    DesireFXCOM_body_01_body_0: THREE.Mesh
    DesireFXCOM_black_matt_14_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_34_black_shiny_0: THREE.Mesh
    DesireFXCOM_silver_08_silver_0: THREE.Mesh
    DesireFXCOM_silver_24_silver_0: THREE.Mesh
    DesireFXCOM_interior_11_interior_0: THREE.Mesh
    DesireFXCOM_black_shiny_26_black_shiny_0: THREE.Mesh
    DesireFXCOM_interior_b_02_interior_b_0: THREE.Mesh
    DesireFXCOM_black_shiny_17_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_shiny_09_black_shiny_0: THREE.Mesh
    DesireFXCOM_chrome_20_chrome_0: THREE.Mesh
    DesireFXCOM_interior_08_interior_0: THREE.Mesh
    DesireFXCOM_chrome_06_chrome_0: THREE.Mesh
    DesireFXCOM_black_matt_49_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_31_silver_0: THREE.Mesh
    DesireFXCOM_silver_32_silver_0: THREE.Mesh
    DesireFXCOM_tex_01_02_tex_01_0: THREE.Mesh
    DesireFXCOM_black_shiny_35_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_05_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_09_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_15_silver_0: THREE.Mesh
    DesireFXCOM_silver_12_silver_0: THREE.Mesh
    DesireFXCOM_body_07_body_0: THREE.Mesh
    DesireFXCOM_black_shiny_06_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_06_black_0: THREE.Mesh
    DesireFXCOM_silver_14_silver_0: THREE.Mesh
    DesireFXCOM_black_shiny_12_black_shiny_0: THREE.Mesh
    DesireFXCOM_silver_22_silver_0: THREE.Mesh
    DesireFXCOM_chrome_08_chrome_0: THREE.Mesh
    DesireFXCOM_black_shiny_31_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_shiny_32_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_43_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_10_silver_0: THREE.Mesh
    DesireFXCOM_glass_04_glass_0: THREE.Mesh
    DesireFXCOM_chrome_09_chrome_0: THREE.Mesh
    DesireFXCOM_silver_26_silver_0: THREE.Mesh
    DesireFXCOM_glass_05_glass_0: THREE.Mesh
    DesireFXCOM_black_matt_41_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_21_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_46_black_matt_0: THREE.Mesh
    DesireFXCOM_body_03_body_0: THREE.Mesh
    DesireFXCOM_black_shiny_13_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_14_black_0: THREE.Mesh
    DesireFXCOM_black_shiny_10_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_29_black_matt_0: THREE.Mesh
    DesireFXCOM_silver_09_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_39_black_matt_0: THREE.Mesh
    DesireFXCOM_black_11_black_0: THREE.Mesh
    DesireFXCOM_d_glass_03_d_glass_0: THREE.Mesh
    DesireFXCOM_black_matt_45_black_matt_0: THREE.Mesh
    DesireFXCOM_black_02_black_0: THREE.Mesh
    DesireFXCOM_interior_12_interior_0: THREE.Mesh
    DesireFXCOM_silver_17_silver_0: THREE.Mesh
    DesireFXCOM_silver_23_silver_0: THREE.Mesh
    DesireFXCOM_black_matt_12_black_matt_0: THREE.Mesh
    DesireFXCOM_black_12_black_0: THREE.Mesh
    DesireFXCOM_black_matt_17_black_matt_0: THREE.Mesh
    DesireFXCOM_black_13_black_0: THREE.Mesh
    DesireFXCOM_black_shiny_30_black_shiny_0: THREE.Mesh
    DesireFXCOM_interior_14_interior_0: THREE.Mesh
    DesireFXCOM_black_matt_44_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_25_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_27_black_matt_0: THREE.Mesh
    DesireFXCOM_body_14_body_0: THREE.Mesh
    DesireFXCOM_black_shiny_22_black_shiny_0: THREE.Mesh
    DesireFXCOM_chrome_13_chrome_0: THREE.Mesh
    DesireFXCOM_black_shiny_07_black_shiny_0: THREE.Mesh
    DesireFXCOM_glass_06_glass_0: THREE.Mesh
    DesireFXCOM_glass_bump_01_glass_bump_0: THREE.Mesh
    DesireFXCOM_glass_08_glass_0: THREE.Mesh
    DesireFXCOM_chrome_21_chrome_0: THREE.Mesh
    DesireFXCOM_glass_07_glass_0: THREE.Mesh
    DesireFXCOM_chrome_03_chrome_0: THREE.Mesh
    DesireFXCOM_plate_02_plate_0: THREE.Mesh
    DesireFXCOM_black_shiny_05_black_shiny_0: THREE.Mesh
    DesireFXCOM_interior_b_03_interior_b_0: THREE.Mesh
    DesireFXCOM_body_13_body_0: THREE.Mesh
    DesireFXCOM_b_glass_bump_01_b_glass_bump_0: THREE.Mesh
    DesireFXCOM_body_08_body_0: THREE.Mesh
    DesireFXCOM_body_06_body_0: THREE.Mesh
    DesireFXCOM_body_05_body_0: THREE.Mesh
    DesireFXCOM_interior_07_interior_0: THREE.Mesh
    DesireFXCOM_r_glass_05_r_glass_0: THREE.Mesh
    DesireFXCOM_glass_01_glass_0: THREE.Mesh
    DesireFXCOM_lights_01_lights_0: THREE.Mesh
    DesireFXCOM_glass_02_glass_0: THREE.Mesh
    DesireFXCOM_glass_bump_03_glass_bump_0: THREE.Mesh
    DesireFXCOM_black_matt_03_black_matt_0: THREE.Mesh
    DesireFXCOM_chrome_05_chrome_0: THREE.Mesh
    DesireFXCOM_chrome_26_chrome_0: THREE.Mesh
    DesireFXCOM_black_matt_22_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_23_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_matt_30_black_matt_0: THREE.Mesh
    DesireFXCOM_chrome_17_chrome_0: THREE.Mesh
    DesireFXCOM_black_shiny_04_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_shiny_02_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_08_black_0: THREE.Mesh
    DesireFXCOM_chrome_23_chrome_0: THREE.Mesh
    DesireFXCOM_black_shiny_27_black_shiny_0: THREE.Mesh
    DesireFXCOM_black_01_black_0: THREE.Mesh
    DesireFXCOM_black_matt_20_black_matt_0: THREE.Mesh
    DesireFXCOM_body_12_body_0: THREE.Mesh
    DesireFXCOM_black_matt_21_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_04_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_02_black_matt_0: THREE.Mesh
    DesireFXCOM_black_shiny_03_black_shiny_0: THREE.Mesh
    DesireFXCOM_chrome_14_chrome_0: THREE.Mesh
    DesireFXCOM_black_shiny_01_black_shiny_0: THREE.Mesh
    DesireFXCOM_chrome_04_chrome_0: THREE.Mesh
    DesireFXCOM_black_matt_01_black_matt_0: THREE.Mesh
    DesireFXCOM_black_matt_34_black_matt_0: THREE.Mesh
  }
  materials: {
    black_matt: THREE.MeshStandardMaterial
    tire_mat4: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    black_shiny: THREE.MeshStandardMaterial
    brakes2: THREE.MeshStandardMaterial
    silver_d: THREE.MeshStandardMaterial
    brakes1: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    glass_bump: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    r_lights: THREE.MeshStandardMaterial
    r_glass: THREE.MeshStandardMaterial
    d_red: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    red_bump: THREE.MeshStandardMaterial
    d_glass: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    plate: THREE.MeshStandardMaterial
    vd_glass: THREE.MeshStandardMaterial
    interior_b: THREE.MeshStandardMaterial
    tex_01: THREE.MeshStandardMaterial
    b_glass_bump: THREE.MeshStandardMaterial
    lights: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function S63(props: any) {
  const { nodes, materials } = useGLTF('/models/s63.glb') as GLTFResult;
  useEffect(() => {
    // car paint
    materials.body.color = new THREE.Color(props.color.hexCode)
    materials.body.roughness = 0
    materials.body.metalness = 0.1
    materials["d_glass"].roughness =0
    materials["d_glass"].metalness =1

     materials["glass"].roughness =1
     materials["glass"].color = new THREE.Color("black")
     materials["d_glass"].color = new THREE.Color("black")
     materials["vd_glass"].color = new THREE.Color(props.color.hexCode)
     materials["black_shiny"].color = new THREE.Color("black")
     materials["black_shiny"].roughness =  0
     materials["black_shiny"].metalness =  1
     materials["chrome"].color = new THREE.Color("black")
    materials["glass"].transparent =true
    materials["r_glass"].transparent =false
    console.log(materials["d_glass"])
  }, [materials, props]);
  return (
    <group {...props} dispose={null} scale={1.7} position={[0, 0, 0]}>
      <mesh name="DesireFXCOM_black_matt_06_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_06_black_matt_0.geometry} material={materials.black_matt} position={[1.582, -0.512, 3.11]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_36_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_36_black_matt_0.geometry} material={materials.black_matt} position={[1.865, -1.041, 3.136]} scale={0.021} />
      <mesh name="DesireFXCOM_tire_mat4_01_tire_mat4_0" geometry={nodes.DesireFXCOM_tire_mat4_01_tire_mat4_0.geometry} material={materials.tire_mat4} position={[1.63, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_19_silver_0" geometry={nodes.DesireFXCOM_silver_19_silver_0.geometry} material={materials.silver} position={[1.695, -0.513, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_24_chrome_0" geometry={nodes.DesireFXCOM_chrome_24_chrome_0.geometry} material={materials.chrome} position={[1.817, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_20_silver_0" geometry={nodes.DesireFXCOM_silver_20_silver_0.geometry} material={materials.silver} position={[1.878, -0.512, 3.138]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_37_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_37_black_matt_0.geometry} material={materials.black_matt} position={[1.793, -0.499, 3.138]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_29_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_29_black_shiny_0.geometry} material={materials.black_shiny} position={[1.816, -0.512, 3.138]} scale={0.021} />
      <mesh name="DesireFXCOM_brakes2_02_brakes2_0" geometry={nodes.DesireFXCOM_brakes2_02_brakes2_0.geometry} material={materials.brakes2} position={[1.657, -0.513, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_28_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_28_black_shiny_0.geometry} material={materials.black_shiny} position={[1.628, -0.512, 3.138]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_47_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_47_black_matt_0.geometry} material={materials.black_matt} position={[1.654, -0.513, 2.782]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_d_03_silver_d_0" geometry={nodes.DesireFXCOM_silver_d_03_silver_d_0.geometry} material={materials.silver_d} position={[1.653, -0.513, 2.794]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_07_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_07_black_matt_0.geometry} material={materials.black_matt} position={[1.655, -0.513, 2.812]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_11_chrome_0" geometry={nodes.DesireFXCOM_chrome_11_chrome_0.geometry} material={materials.chrome} position={[1.817, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_13_silver_0" geometry={nodes.DesireFXCOM_silver_13_silver_0.geometry} material={materials.silver} position={[1.878, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_tire_mat4_03_tire_mat4_0" geometry={nodes.DesireFXCOM_tire_mat4_03_tire_mat4_0.geometry} material={materials.tire_mat4} position={[1.63, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_18_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_18_black_matt_0.geometry} material={materials.black_matt} position={[1.793, -0.499, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_14_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_14_black_shiny_0.geometry} material={materials.black_shiny} position={[1.628, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_brakes1_01_brakes1_0" geometry={nodes.DesireFXCOM_brakes1_01_brakes1_0.geometry} material={materials.brakes1} position={[1.592, -0.513, -3.326]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_19_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_19_black_matt_0.geometry} material={materials.black_matt} position={[1.865, -1.041, -3.326]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_16_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_16_black_shiny_0.geometry} material={materials.black_shiny} position={[1.816, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_32_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_32_black_matt_0.geometry} material={materials.black_matt} position={[1.579, -0.513, -3.314]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_d_01_silver_d_0" geometry={nodes.DesireFXCOM_silver_d_01_silver_d_0.geometry} material={materials.silver_d} position={[1.593, -0.613, -3.014]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_33_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_33_black_matt_0.geometry} material={materials.black_matt} position={[1.592, -0.61, -3.013]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_27_chrome_0" geometry={nodes.DesireFXCOM_chrome_27_chrome_0.geometry} material={materials.chrome} position={[-1.942, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_29_silver_0" geometry={nodes.DesireFXCOM_silver_29_silver_0.geometry} material={materials.silver} position={[-1.821, -0.513, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_51_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_51_black_matt_0.geometry} material={materials.black_matt} position={[-1.78, -0.513, 2.782]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_d_04_silver_d_0" geometry={nodes.DesireFXCOM_silver_d_04_silver_d_0.geometry} material={materials.silver_d} position={[-1.779, -0.513, 2.794]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_48_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_48_black_matt_0.geometry} material={materials.black_matt} position={[-1.78, -0.513, 2.812]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_50_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_50_black_matt_0.geometry} material={materials.black_matt} position={[-1.708, -0.512, 3.11]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_26_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_26_black_matt_0.geometry} material={materials.black_matt} position={[-1.99, -1.041, 3.136]} scale={0.021} />
      <mesh name="DesireFXCOM_tire_mat4_04_tire_mat4_0" geometry={nodes.DesireFXCOM_tire_mat4_04_tire_mat4_0.geometry} material={materials.tire_mat4} position={[-1.755, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_36_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_36_black_shiny_0.geometry} material={materials.black_shiny} position={[-1.942, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_24_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_24_black_matt_0.geometry} material={materials.black_matt} position={[-1.919, -0.499, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_35_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_35_black_matt_0.geometry} material={materials.black_matt} position={[-1.761, -0.513, -3.314]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_27_silver_0" geometry={nodes.DesireFXCOM_silver_27_silver_0.geometry} material={materials.silver} position={[-2.004, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_38_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_38_black_matt_0.geometry} material={materials.black_matt} position={[-1.919, -0.499, 3.138]} scale={0.021} />
      <mesh name="DesireFXCOM_brakes2_01_brakes2_0" geometry={nodes.DesireFXCOM_brakes2_01_brakes2_0.geometry} material={materials.brakes2} position={[-1.782, -0.513, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_33_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_33_black_shiny_0.geometry} material={materials.black_shiny} position={[-1.753, -0.512, 3.137]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_21_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_21_black_shiny_0.geometry} material={materials.black_shiny} position={[-1.753, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_brakes1_02_brakes1_0" geometry={nodes.DesireFXCOM_brakes1_02_brakes1_0.geometry} material={materials.brakes1} position={[-1.773, -0.513, -3.326]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_15_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_15_black_matt_0.geometry} material={materials.black_matt} position={[-1.99, -1.041, -3.326]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_15_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_15_black_shiny_0.geometry} material={materials.black_shiny} position={[-1.942, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_tire_mat4_02_tire_mat4_0" geometry={nodes.DesireFXCOM_tire_mat4_02_tire_mat4_0.geometry} material={materials.tire_mat4} position={[-1.755, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_10_chrome_0" geometry={nodes.DesireFXCOM_chrome_10_chrome_0.geometry} material={materials.chrome} position={[-1.942, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_18_silver_0" geometry={nodes.DesireFXCOM_silver_18_silver_0.geometry} material={materials.silver} position={[-2.004, -0.512, -3.325]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_d_02_silver_d_0" geometry={nodes.DesireFXCOM_silver_d_02_silver_d_0.geometry} material={materials.silver_d} position={[-1.775, -0.613, -3.014]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_31_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_31_black_matt_0.geometry} material={materials.black_matt} position={[-1.773, -0.61, -3.013]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_25_chrome_0" geometry={nodes.DesireFXCOM_chrome_25_chrome_0.geometry} material={materials.chrome} position={[-0.062, 0.851, -5.624]} scale={0.021} />
      <mesh name="DesireFXCOM_body_02_body_0" geometry={nodes.DesireFXCOM_body_02_body_0.geometry} material={materials.body} position={[-0.063, 0.411, -5.624]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_28_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_28_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.486, -5.619]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_03_glass_0" geometry={nodes.DesireFXCOM_glass_03_glass_0.geometry} material={materials.glass} position={[-0.063, 0.669, -5.616]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_bump_02_glass_bump_0" geometry={nodes.DesireFXCOM_glass_bump_02_glass_bump_0.geometry} material={materials.glass_bump} position={[-0.063, 0.669, -5.615]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_12_chrome_0" geometry={nodes.DesireFXCOM_chrome_12_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.669, -5.615]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_01_chrome_0" geometry={nodes.DesireFXCOM_chrome_01_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.669, -5.612]} scale={0.021} />
      <mesh name="DesireFXCOM_black_10_black_0" geometry={nodes.DesireFXCOM_black_10_black_0.geometry} material={materials.black} position={[-0.063, -0.486, -5.541]} scale={0.021} />
      <mesh name="DesireFXCOM_r_lights_02_r_lights_0" geometry={nodes.DesireFXCOM_r_lights_02_r_lights_0.geometry} material={materials.r_lights} position={[-0.063, 0.575, -5.316]} scale={0.021} />
      <mesh name="DesireFXCOM_r_glass_03_r_glass_0" geometry={nodes.DesireFXCOM_r_glass_03_r_glass_0.geometry} material={materials.r_glass} position={[-0.063, 0.651, -5.312]} scale={0.021} />
      <mesh name="DesireFXCOM_r_lights_01_r_lights_0" geometry={nodes.DesireFXCOM_r_lights_01_r_lights_0.geometry} material={materials.r_lights} position={[-0.063, 0.575, -5.316]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_22_chrome_0" geometry={nodes.DesireFXCOM_chrome_22_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.702, -5.289]} scale={0.021} />
      <mesh name="DesireFXCOM_body_09_body_0" geometry={nodes.DesireFXCOM_body_09_body_0.geometry} material={materials.body} position={[-0.063, -0.077, -5.28]} scale={0.021} />
      <mesh name="DesireFXCOM_r_glass_02_r_glass_0" geometry={nodes.DesireFXCOM_r_glass_02_r_glass_0.geometry} material={materials.r_glass} position={[-0.063, 0.623, -5.279]} scale={0.021} />
      <mesh name="DesireFXCOM_d_red_01_d_red_0" geometry={nodes.DesireFXCOM_d_red_01_d_red_0.geometry} material={materials.d_red} position={[-0.063, 0.561, -5.22]} scale={0.021} />
      <mesh name="DesireFXCOM_red_02_red_0" geometry={nodes.DesireFXCOM_red_02_red_0.geometry} material={materials.red} position={[-0.063, 0.554, -5.201]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_16_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_16_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.556, -5.197]} scale={0.021} />
      <mesh name="DesireFXCOM_r_glass_01_r_glass_0" geometry={nodes.DesireFXCOM_r_glass_01_r_glass_0.geometry} material={materials.r_glass} position={[-0.063, 0.556, -5.197]} scale={0.021} />
      <mesh name="DesireFXCOM_black_07_black_0" geometry={nodes.DesireFXCOM_black_07_black_0.geometry} material={materials.black} position={[-0.063, 0.556, -5.157]} scale={0.021} />
      <mesh name="DesireFXCOM_body_10_body_0" geometry={nodes.DesireFXCOM_body_10_body_0.geometry} material={materials.body} position={[-0.063, 0.923, -4.963]} scale={0.021} />
      <mesh name="DesireFXCOM_red_bump_01_red_bump_0" geometry={nodes.DesireFXCOM_red_bump_01_red_bump_0.geometry} material={materials.red_bump} position={[-0.063, 0.625, -4.94]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_23_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_23_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 1.083, -4.408]} scale={0.021} />
      <mesh name="DesireFXCOM_d_glass_02_d_glass_0" geometry={nodes.DesireFXCOM_d_glass_02_d_glass_0.geometry} material={materials.d_glass} position={[-0.063, 1.389, -3.827]} scale={0.021} />
      <mesh name="DesireFXCOM_black_09_black_0" geometry={nodes.DesireFXCOM_black_09_black_0.geometry} material={materials.black} position={[-0.063, 1.389, -3.825]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_09_interior_0" geometry={nodes.DesireFXCOM_interior_09_interior_0.geometry} material={materials.interior} position={[-0.063, 1.613, -3.33]} scale={0.021} />
      <mesh name="DesireFXCOM_red_01_red_0" geometry={nodes.DesireFXCOM_red_01_red_0.geometry} material={materials.red} position={[-0.063, 1.615, -3.258]} scale={0.021} />
      <mesh name="DesireFXCOM_r_glass_04_r_glass_0" geometry={nodes.DesireFXCOM_r_glass_04_r_glass_0.geometry} material={materials.r_glass} position={[-0.063, 1.617, -3.252]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_11_silver_0" geometry={nodes.DesireFXCOM_silver_11_silver_0.geometry} material={materials.silver} position={[-0.063, 0.966, -3.212]} scale={0.021} />
      <mesh name="DesireFXCOM_body_11_body_0" geometry={nodes.DesireFXCOM_body_11_body_0.geometry} material={materials.body} position={[-0.063, 1.713, -2.819]} scale={0.021} />
      <mesh name="DesireFXCOM_black_04_black_0" geometry={nodes.DesireFXCOM_black_04_black_0.geometry} material={materials.black} position={[-0.063, 1.253, -2.766]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_13_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_13_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.394, -1.832]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_13_interior_0" geometry={nodes.DesireFXCOM_interior_13_interior_0.geometry} material={materials.interior} position={[-0.063, 0.331, -1.787]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_02_chrome_0" geometry={nodes.DesireFXCOM_chrome_02_chrome_0.geometry} material={materials.chrome} position={[-0.063, -0.496, -1.607]} scale={0.021} />
      <mesh name="DesireFXCOM_body_15_body_0" geometry={nodes.DesireFXCOM_body_15_body_0.geometry} material={materials.body} position={[-1.122, -0.258, -5.752]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_18_chrome_0" geometry={nodes.DesireFXCOM_chrome_18_chrome_0.geometry} material={materials.chrome} position={[-0.063, -0.466, -5.675]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_19_chrome_0" geometry={nodes.DesireFXCOM_chrome_19_chrome_0.geometry} material={materials.chrome} position={[-0.063, -0.486, -5.671]} scale={0.021} />

      <mesh name="DesireFXCOM_r_glass_06_r_glass_0" geometry={nodes.DesireFXCOM_r_glass_06_r_glass_0.geometry} material={materials.r_glass} position={[-0.063, 0.025, -5.644]} scale={0.021} />
      <mesh name="DesireFXCOM_red_bump_02_red_bump_0" geometry={nodes.DesireFXCOM_red_bump_02_red_bump_0.geometry} material={materials.red_bump} position={[-0.063, 0.025, -5.642]} scale={0.021} />
      <mesh name="DesireFXCOM_body_04_body_0" geometry={nodes.DesireFXCOM_body_04_body_0.geometry} material={materials.body} position={[0.221, 0.672, -5.638]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_30_silver_0" geometry={nodes.DesireFXCOM_silver_30_silver_0.geometry} material={materials.silver} position={[-0.063, 0.382, -1.51]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_11_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_11_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.057, -1.426]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_16_chrome_0" geometry={nodes.DesireFXCOM_chrome_16_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.605, -1.41]} scale={0.021} />
      <mesh name="DesireFXCOM_black_90_black_0" geometry={nodes.DesireFXCOM_black_90_black_0.geometry} material={materials.black} position={[-0.063, 0.973, -1.288]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_15_interior_0" geometry={nodes.DesireFXCOM_interior_15_interior_0.geometry} material={materials.interior} position={[0.487, 1.774, -1.377]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_03_interior_0" geometry={nodes.DesireFXCOM_interior_03_interior_0.geometry} material={materials.interior} position={[-0.063, 0.285, -1.337]} scale={0.021} />
      <mesh name="DesireFXCOM_vd_glass_90_vd_glass_0" geometry={nodes.DesireFXCOM_vd_glass_90_vd_glass_0.geometry} material={materials.vd_glass} position={[-0.063, 1.78, -1.12]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_05_silver_0" geometry={nodes.DesireFXCOM_silver_05_silver_0.geometry} material={materials.silver} position={[-0.063, 0.943, -1.299]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_04_interior_0" geometry={nodes.DesireFXCOM_interior_04_interior_0.geometry} material={materials.interior} position={[-0.063, 0.973, -1.288]} scale={0.021} />
      <mesh name="DesireFXCOM_red_03_red_0" geometry={nodes.DesireFXCOM_red_03_red_0.geometry} material={materials.red} position={[-0.079, -0.088, -1.275]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_52_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_52_black_matt_0.geometry} material={materials.black_matt} position={[0.77, 0.943, -1.272]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_10_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_10_black_matt_0.geometry} material={materials.black_matt} position={[-0.172, 0.943, -1.232]} scale={0.021} />
      <mesh name="DesireFXCOM_d_glass_01_d_glass_0" geometry={nodes.DesireFXCOM_d_glass_01_d_glass_0.geometry} material={materials.d_glass} position={[-0.063, 1.273, -1.051]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_11_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_11_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.775, -0.998]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_07_silver_0" geometry={nodes.DesireFXCOM_silver_07_silver_0.geometry} material={materials.silver} position={[-0.063, 0.759, -0.987]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_25_silver_0" geometry={nodes.DesireFXCOM_silver_25_silver_0.geometry} material={materials.silver} position={[-0.063, 0.763, -0.965]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_28_silver_0" geometry={nodes.DesireFXCOM_silver_28_silver_0.geometry} material={materials.silver} position={[-0.063, 0.263, -0.949]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_18_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_18_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.261, -0.945]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_40_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_40_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.764, -0.945]} scale={0.021} />
      <mesh name="DesireFXCOM_black_15_black_0" geometry={nodes.DesireFXCOM_black_15_black_0.geometry} material={materials.black} position={[-0.063, 0.774, -0.932]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_02_interior_0" geometry={nodes.DesireFXCOM_interior_02_interior_0.geometry} material={materials.interior} position={[-0.063, -0.108, -0.905]} scale={0.021} />
      <mesh name="DesireFXCOM_black_03_black_0" geometry={nodes.DesireFXCOM_black_03_black_0.geometry} material={materials.black} position={[-0.063, 0.324, -0.893]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_07_chrome_0" geometry={nodes.DesireFXCOM_chrome_07_chrome_0.geometry} material={materials.chrome} position={[-0.063, 1.277, -0.866]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_15_chrome_0" geometry={nodes.DesireFXCOM_chrome_15_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.865, -0.859]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_b_01_interior_b_0" geometry={nodes.DesireFXCOM_interior_b_01_interior_b_0.geometry} material={materials.interior_b} position={[-0.063, 0.47, -0.814]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_02_silver_0" geometry={nodes.DesireFXCOM_silver_02_silver_0.geometry} material={materials.silver} position={[-0.063, 0.471, -0.778]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_42_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_42_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.616, -0.756]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_01_silver_0" geometry={nodes.DesireFXCOM_silver_01_silver_0.geometry} material={materials.silver} position={[-0.063, 0.615, -0.674]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_10_interior_0" geometry={nodes.DesireFXCOM_interior_10_interior_0.geometry} material={materials.interior} position={[-0.063, 0.773, -0.581]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_19_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_19_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.607, -0.578]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_06_silver_0" geometry={nodes.DesireFXCOM_silver_06_silver_0.geometry} material={materials.silver} position={[-0.063, 0.789, -0.576]} scale={0.021} />
      <mesh name="DesireFXCOM_black_05_black_0" geometry={nodes.DesireFXCOM_black_05_black_0.geometry} material={materials.black} position={[-0.063, -0.297, -0.507]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_01_interior_0" geometry={nodes.DesireFXCOM_interior_01_interior_0.geometry} material={materials.interior} position={[1.119, 1.642, -0.505]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_05_interior_0" geometry={nodes.DesireFXCOM_interior_05_interior_0.geometry} material={materials.interior} position={[-0.063, -0.136, -0.497]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_24_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_24_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 1.259, -0.475]} scale={0.021} />
      <mesh name="DesireFXCOM_tex_01_03_tex_01_0" geometry={nodes.DesireFXCOM_tex_01_03_tex_01_0.geometry} material={materials.tex_01} position={[-0.063, 0.636, -0.418]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_16_silver_0" geometry={nodes.DesireFXCOM_silver_16_silver_0.geometry} material={materials.silver} position={[-0.063, 0.36, -0.416]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_04_silver_0" geometry={nodes.DesireFXCOM_silver_04_silver_0.geometry} material={materials.silver} position={[-0.06, 0.419, -0.401]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_08_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_08_black_matt_0.geometry} material={materials.black_matt} position={[-0.06, 0.427, -0.394]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_25_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_25_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 1.356, -0.346]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_08_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_08_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.492, -0.308]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_03_silver_0" geometry={nodes.DesireFXCOM_silver_03_silver_0.geometry} material={materials.silver} position={[-0.063, 0.565, -0.127]} scale={0.021} />
      <mesh name="DesireFXCOM_tex_01_01_tex_01_0" geometry={nodes.DesireFXCOM_tex_01_01_tex_01_0.geometry} material={materials.tex_01} position={[-0.038, 0.636, -0.098]} scale={0.021} />
      <mesh name="DesireFXCOM_body_01_body_0" geometry={nodes.DesireFXCOM_body_01_body_0.geometry} material={materials.body} position={[-0.063, -0.744, -0.095]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_14_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_14_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.276, -0.046]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_34_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_34_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 1.632, 0.045]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_08_silver_0" geometry={nodes.DesireFXCOM_silver_08_silver_0.geometry} material={materials.silver} position={[-0.063, 0.309, 0.054]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_24_silver_0" geometry={nodes.DesireFXCOM_silver_24_silver_0.geometry} material={materials.silver} position={[-0.063, 1.653, 0.067]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_11_interior_0" geometry={nodes.DesireFXCOM_interior_11_interior_0.geometry} material={materials.interior} position={[0.621, 1.602, 0.153]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_26_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_26_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 1.78, -1.12]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_b_02_interior_b_0" geometry={nodes.DesireFXCOM_interior_b_02_interior_b_0.geometry} material={materials.interior_b} position={[-0.061, 0.32, 0.165]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_17_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_17_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.354, 0.29]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_09_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_09_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.337, 0.305]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_20_chrome_0" geometry={nodes.DesireFXCOM_chrome_20_chrome_0.geometry} material={materials.chrome} position={[-0.062, 1.419, 0.432]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_08_interior_0" geometry={nodes.DesireFXCOM_interior_08_interior_0.geometry} material={materials.interior} position={[-0.062, 1.438, 0.48]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_06_chrome_0" geometry={nodes.DesireFXCOM_chrome_06_chrome_0.geometry} material={materials.chrome} position={[0.77, 0.712, 0.483]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_49_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_49_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.485, 0.49]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_31_silver_0" geometry={nodes.DesireFXCOM_silver_31_silver_0.geometry} material={materials.silver} position={[-0.063, 0.503, 0.494]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_32_silver_0" geometry={nodes.DesireFXCOM_silver_32_silver_0.geometry} material={materials.silver} position={[0.77, 0.571, 0.5]} scale={0.021} />
      <mesh name="DesireFXCOM_tex_01_02_tex_01_0" geometry={nodes.DesireFXCOM_tex_01_02_tex_01_0.geometry} material={materials.tex_01} position={[0.77, 0.716, 0.527]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_35_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_35_black_shiny_0.geometry} material={materials.black_shiny} position={[0.77, 0.73, 0.528]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_05_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_05_black_matt_0.geometry} material={materials.black_matt} position={[0.77, 0.729, 0.563]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_09_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_09_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 1.512, 0.582]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_15_silver_0" geometry={nodes.DesireFXCOM_silver_15_silver_0.geometry} material={materials.silver} position={[-0.063, 0.411, 0.61]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_12_silver_0" geometry={nodes.DesireFXCOM_silver_12_silver_0.geometry} material={materials.silver} position={[0.77, 0.777, 0.694]} scale={0.021} />
      <mesh name="DesireFXCOM_body_07_body_0" geometry={nodes.DesireFXCOM_body_07_body_0.geometry} material={materials.body} position={[-0.063, 0.599, 3.269]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_06_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_06_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.24, 4.066]} scale={0.021} />
      <mesh name="DesireFXCOM_black_06_black_0" geometry={nodes.DesireFXCOM_black_06_black_0.geometry} material={materials.black} position={[-0.063, 0.242, 4.085]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_14_silver_0" geometry={nodes.DesireFXCOM_silver_14_silver_0.geometry} material={materials.silver} position={[-0.063, 0.264, 4.098]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_12_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_12_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 1.011, 0.838]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_22_silver_0" geometry={nodes.DesireFXCOM_silver_22_silver_0.geometry} material={materials.silver} position={[-0.063, 0.554, 0.842]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_08_chrome_0" geometry={nodes.DesireFXCOM_chrome_08_chrome_0.geometry} material={materials.chrome} position={[-0.063, 1.011, 0.844]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_31_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_31_black_shiny_0.geometry} material={materials.black_shiny} position={[1.5, 0.625, 0.848]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_32_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_32_black_shiny_0.geometry} material={materials.black_shiny} position={[1.272, 0.487, 0.862]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_43_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_43_black_matt_0.geometry} material={materials.black_matt} position={[1.359, 0.591, 0.893]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_10_silver_0" geometry={nodes.DesireFXCOM_silver_10_silver_0.geometry} material={materials.silver} position={[0.891, 0.623, 0.905]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_04_glass_0" geometry={nodes.DesireFXCOM_glass_04_glass_0.geometry} material={materials.glass} position={[-0.063, 0.962, 0.966]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_09_chrome_0" geometry={nodes.DesireFXCOM_chrome_09_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.962, 0.966]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_26_silver_0" geometry={nodes.DesireFXCOM_silver_26_silver_0.geometry} material={materials.silver} position={[-0.063, 0.649, 0.966]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_05_glass_0" geometry={nodes.DesireFXCOM_glass_05_glass_0.geometry} material={materials.glass} position={[-0.063, 0.962, 0.968]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_41_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_41_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.635, 0.975]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_21_silver_0" geometry={nodes.DesireFXCOM_silver_21_silver_0.geometry} material={materials.silver} position={[-0.64, 0.42, 0.984]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_46_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_46_black_matt_0.geometry} material={materials.black_matt} position={[0.77, 0.523, 0.983]} scale={0.021} />
      <mesh name="DesireFXCOM_body_03_body_0" geometry={nodes.DesireFXCOM_body_03_body_0.geometry} material={materials.body} position={[-0.063, 1.068, 0.994]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_13_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_13_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.909, 0.995]} scale={0.021} />
      <mesh name="DesireFXCOM_black_14_black_0" geometry={nodes.DesireFXCOM_black_14_black_0.geometry} material={materials.black} position={[-0.063, 0.628, 0.99]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_10_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_10_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.645, 1.003]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_29_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_29_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 1.204, 1.068]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_09_silver_0" geometry={nodes.DesireFXCOM_silver_09_silver_0.geometry} material={materials.silver} position={[0.77, 0.849, 1.082]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_39_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_39_black_matt_0.geometry} material={materials.black_matt} position={[0.77, 0.848, 1.1]} scale={0.021} />
      <mesh name="DesireFXCOM_black_11_black_0" geometry={nodes.DesireFXCOM_black_11_black_0.geometry} material={materials.black} position={[-0.063, 1.205, 1.158]} scale={0.021} />
      <mesh name="DesireFXCOM_d_glass_03_d_glass_0" geometry={nodes.DesireFXCOM_d_glass_03_d_glass_0.geometry} material={materials.d_glass} position={[-0.063, 1.206, 1.159]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_45_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_45_black_matt_0.geometry} material={materials.black_matt} position={[0.77, 0.807, 1.164]} scale={0.021} />
      <mesh name="DesireFXCOM_black_02_black_0" geometry={nodes.DesireFXCOM_black_02_black_0.geometry} material={materials.black} position={[0.77, 0.448, 1.176]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_12_interior_0" geometry={nodes.DesireFXCOM_interior_12_interior_0.geometry} material={materials.interior} position={[0.774, 0.876, 1.223]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_17_silver_0" geometry={nodes.DesireFXCOM_silver_17_silver_0.geometry} material={materials.silver} position={[-0.063, 0.845, 1.253]} scale={0.021} />
      <mesh name="DesireFXCOM_silver_23_silver_0" geometry={nodes.DesireFXCOM_silver_23_silver_0.geometry} material={materials.silver} position={[-0.063, 0.844, 1.257]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_12_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_12_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.844, 1.267]} scale={0.021} />
      <mesh name="DesireFXCOM_black_12_black_0" geometry={nodes.DesireFXCOM_black_12_black_0.geometry} material={materials.black} position={[-0.063, 0.844, 1.27]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_17_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_17_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.839, 1.451]} scale={0.021} />
      <mesh name="DesireFXCOM_black_13_black_0" geometry={nodes.DesireFXCOM_black_13_black_0.geometry} material={materials.black} position={[-0.063, 0.827, 1.458]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_30_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_30_black_shiny_0.geometry} material={materials.black_shiny} position={[0.774, 0.745, 1.462]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_14_interior_0" geometry={nodes.DesireFXCOM_interior_14_interior_0.geometry} material={materials.interior} position={[-0.063, 0.105, 1.538]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_44_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_44_black_matt_0.geometry} material={materials.black_matt} position={[0.578, -0.231, 1.583]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_25_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_25_black_matt_0.geometry} material={materials.black_matt} position={[-0.211, 0.813, 1.951]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_27_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_27_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.807, 2.036]} scale={0.021} />
      <mesh name="DesireFXCOM_body_14_body_0" geometry={nodes.DesireFXCOM_body_14_body_0.geometry} material={materials.body} position={[-0.063, 0.127, 2.765]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_22_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_22_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.244, 4.108]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_13_chrome_0" geometry={nodes.DesireFXCOM_chrome_13_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.239, 4.158]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_07_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_07_black_shiny_0.geometry} material={materials.black_shiny} position={[1.435, 0.315, 4.177]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_06_glass_0" geometry={nodes.DesireFXCOM_glass_06_glass_0.geometry} material={materials.glass} position={[-0.063, 0.239, 4.248]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_bump_01_glass_bump_0" geometry={nodes.DesireFXCOM_glass_bump_01_glass_bump_0.geometry} material={materials.glass_bump} position={[-0.063, 0.265, 4.235]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_08_glass_0" geometry={nodes.DesireFXCOM_glass_08_glass_0.geometry} material={materials.glass} position={[-0.063, 0.245, 4.25]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_21_chrome_0" geometry={nodes.DesireFXCOM_chrome_21_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.245, 4.262]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_07_glass_0" geometry={nodes.DesireFXCOM_glass_07_glass_0.geometry} material={materials.glass} position={[-0.063, 0.239, 4.248]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_03_chrome_0" geometry={nodes.DesireFXCOM_chrome_03_chrome_0.geometry} material={materials.chrome} position={[-0.063, -0.803, 4.932]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_05_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_05_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.166, -0.054, 4.973]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_b_03_interior_b_0" geometry={nodes.DesireFXCOM_interior_b_03_interior_b_0.geometry} material={materials.interior_b} position={[-0.063, 0.496, -1.358]} scale={0.021} />
      <mesh name="DesireFXCOM_body_13_body_0" geometry={nodes.DesireFXCOM_body_13_body_0.geometry} material={materials.body} position={[-0.063, -0.097, -4.851]} scale={0.021} />
      <mesh name="DesireFXCOM_b_glass_bump_01_b_glass_bump_0" geometry={nodes.DesireFXCOM_b_glass_bump_01_b_glass_bump_0.geometry} material={materials.b_glass_bump} position={[-0.063, 0.215, 4.277]} scale={0.021} />
      <mesh name="DesireFXCOM_body_08_body_0" geometry={nodes.DesireFXCOM_body_08_body_0.geometry} material={materials.body} position={[-0.063, -0.222, 4.257]} scale={0.021} />
      <mesh name="DesireFXCOM_body_06_body_0" geometry={nodes.DesireFXCOM_body_06_body_0.geometry} material={materials.body} position={[-0.063, 0.635, -1.94]} scale={0.021} />
      <mesh name="DesireFXCOM_body_05_body_0" geometry={nodes.DesireFXCOM_body_05_body_0.geometry} material={materials.body} position={[-0.063, 0.115, -0.802]} scale={0.021} />
      <mesh name="DesireFXCOM_interior_07_interior_0" geometry={nodes.DesireFXCOM_interior_07_interior_0.geometry} material={materials.interior} position={[-0.063, 1.262, -0.799]} scale={0.021} />
      <mesh name="DesireFXCOM_r_glass_05_r_glass_0" geometry={nodes.DesireFXCOM_r_glass_05_r_glass_0.geometry} material={materials.r_glass} position={[-0.063, 0.575, -5.316]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_01_glass_0" geometry={nodes.DesireFXCOM_glass_01_glass_0.geometry} material={materials.glass} position={[-0.063, 0.239, 4.248]} scale={0.021} />
      <mesh name="DesireFXCOM_lights_01_lights_0" geometry={nodes.DesireFXCOM_lights_01_lights_0.geometry} material={materials.lights} position={[-0.063, 0.245, 4.266]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_02_glass_0" geometry={nodes.DesireFXCOM_glass_02_glass_0.geometry} material={materials.glass} position={[-0.063, 0.276, 4.318]} scale={0.021} />
      <mesh name="DesireFXCOM_glass_bump_03_glass_bump_0" geometry={nodes.DesireFXCOM_glass_bump_03_glass_bump_0.geometry} material={materials.glass_bump} position={[-0.063, 0.276, 4.328]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_03_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_03_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.881, 4.45]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_05_chrome_0" geometry={nodes.DesireFXCOM_chrome_05_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.225, 4.506]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_26_chrome_0" geometry={nodes.DesireFXCOM_chrome_26_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.595, 4.576]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_22_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_22_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.083, 4.577]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_23_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_23_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, -0.513, 4.664]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_30_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_30_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.523, 4.674]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_17_chrome_0" geometry={nodes.DesireFXCOM_chrome_17_chrome_0.geometry} material={materials.chrome} position={[-0.063, -0.516, 4.677]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_04_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_04_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, -0.512, 4.697]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_02_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_02_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, -0.455, 4.745]} scale={0.021} />
      <mesh name="DesireFXCOM_black_08_black_0" geometry={nodes.DesireFXCOM_black_08_black_0.geometry} material={materials.black} position={[-0.063, -0.593, 4.761]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_23_chrome_0" geometry={nodes.DesireFXCOM_chrome_23_chrome_0.geometry} material={materials.chrome} position={[-0.059, 0.418, 4.801]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_27_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_27_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.059, 0.419, 4.801]} scale={0.021} />
      <mesh name="DesireFXCOM_black_01_black_0" geometry={nodes.DesireFXCOM_black_01_black_0.geometry} material={materials.black} position={[-0.063, 0.019, 4.823]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_20_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_20_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.476, 4.828]} scale={0.021} />
      <mesh name="DesireFXCOM_body_12_body_0" geometry={nodes.DesireFXCOM_body_12_body_0.geometry} material={materials.body} position={[-0.939, -0.273, 4.829]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_21_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_21_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.774, 4.83]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_04_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_04_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.807, 4.859]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_02_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_02_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, 0.016, 4.871]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_03_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_03_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.022, 4.876]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_14_chrome_0" geometry={nodes.DesireFXCOM_chrome_14_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.029, 4.896]} scale={0.021} />
      <mesh name="DesireFXCOM_black_shiny_01_black_shiny_0" geometry={nodes.DesireFXCOM_black_shiny_01_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.063, 0.095, 4.901]} scale={0.021} />
      <mesh name="DesireFXCOM_chrome_04_chrome_0" geometry={nodes.DesireFXCOM_chrome_04_chrome_0.geometry} material={materials.chrome} position={[-0.063, 0.016, 4.911]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_01_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_01_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.215, 4.92]} scale={0.021} />
      <mesh name="DesireFXCOM_black_matt_34_black_matt_0" geometry={nodes.DesireFXCOM_black_matt_34_black_matt_0.geometry} material={materials.black_matt} position={[-0.063, -0.503, 4.929]} scale={0.021} />
    </group>
  )
}

useGLTF.preload('/models/s63.glb')
